# Generated by Django 3.2.10 on 2021-12-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='Product',
        ),
    ]
